# Generated by Django 3.1.5 on 2021-01-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210115_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.CharField(blank=True, choices=[('School', 'School'), ('Work', 'Work'), ('Lifestyle', 'Lifestyle'), ('Organization', 'Organization'), ('Time Management', 'Time Management')], default=None, max_length=100, null=True),
        ),
    ]
