# Generated by Django 3.1.5 on 2021-01-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210113_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
