# Generated by Django 3.1.5 on 2021-01-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210113_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages/'),
        ),
    ]
